services:
  db:
    image: postgres:16
    container_name: superset-db
    restart: always
    env_file: .env
    volumes:
      - superset-db:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # add entry point to create superset tables on postgres db
    networks:
        - superset-net
  redis:
    image: redis:7
    container_name: superset-cache
    restart: always
    volumes:
      - superset-redis:/data
      # - ./redis/redis.conf
    # command: redis-server /usr/local/etc/redis/redis.conf
    networks:
        - superset-net
  superset:
    image: apache/superset:5.0.0
    build: .
    container_name: superset-app
    restart: always
    env_file: .env
    # To upgrade to postgres metadata db.
    command: >
      bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email adminPostgres@admin.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "
    ports:
      - 8088:8088
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes:
      - superset-home:/app/superset_home
    networks:
        - superset-net

  ## Contenedor de inicialización (se ejecuta una sola vez)
  superset-init:
    image: apache/superset:5.0.0
    container_name: superset-init
    command: ["/app/docker/docker-init.sh"]
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - superset-home:/app/superset_home
    networks:
        - superset-net

  ## Worker de Celery: ejecuta tareas pesadas en segundo plano
  superset-worker:
    image: apache/superset:5.0.0
    container_name: superset-worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    restart: always
    depends_on:
      superset-init:
        condition: service_completed_successfully
    env_file: .env
    volumes:
      - superset-home:/app/superset_home
    healthcheck:
      test: ["CMD-SHELL", "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME"]
    networks:
        - superset-net

  # Planificador de Celery: programa tareas periódicas
  superset-worker-beat:
    image: apache/superset:5.0.0
    container_name: superset-worker-beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    restart: always
    depends_on:
      superset-init:
        condition: service_completed_successfully
    env_file: .env
    volumes:
      - superset-home:/app/superset_home
    healthcheck:
      disable: true
    networks:
        - superset-net

  # To check the postgres metadata db.
  pgadmin:
    image: dpage/pgadmin4:latest 
    container_name: pgadmin
    profiles: [pgadmin] # Este servicio solo se activa con el perfil "pgadmin"
    env_file: .env
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json # Mount the servers.json file
    depends_on:
      - db
    networks:
      - superset-net
 

  nginx-http:
    image: nginx:latest
    container_name: superset-nginx-http
    restart: unless-stopped
    profiles: [http, pgadmin] # Este servicio solo se activa con el perfil "http y pgadmin"
    ports:
      - 83:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/superset_http.conf:/etc/nginx/conf.d/superset.conf:ro # Montamos solo la config HTTP
    networks:
      - superset-net
    depends_on:
      - superset

  nginx-ssl:
    image: nginx:latest
    container_name: superset-nginx-ssl
    restart: unless-stopped
    profiles: [ssl] # Este servicio solo se activa con el perfil "ssl"
    ports:
      - 80:80
      - 443:443
    env_file: .env # Carga el .env para usar ${DOMAIN_NAME}
    volumes:
      # Monta la configuración de Nginx y el template de SSL procesado
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/superset_ssl.conf:/etc/nginx/conf.d/superset.conf:ro # Montamos solo la config SSL
      # Monta el directorio de certificados
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - superset-net
    depends_on:
      - superset
volumes:
  superset-home:
  superset-db:
  superset-redis:
  pgadmin:
networks:
  superset-net:
    driver: bridge
