services:
  superset:
    image: apache/superset:6.0.0rc1
    container_name: superset_app
    restart: always
    environment:
      - SUPERSET_SECRET_KEY=clave-local-123
      - DATABASE_DIALECT=postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=superset
      - DATABASE_PASSWORD=superset_pass
      - DATABASE_DB=superset
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    expose:
      - "8088"
    volumes:
      - superset_home:/app/superset_home
    command: >
      bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@admin.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "

  db:
    image: postgres:15
    container_name: superset_db
    restart: always
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset_pass
      - POSTGRES_DB=superset
    volumes:
      - superset_db:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: superset_redis
    restart: always
    volumes:
      - superset_redis:/data

  nginx:
    image: nginx:1.27
    container_name: superset_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - superset

volumes:
  superset_home:
  superset_db:
  superset_redis:
