services:
  nginx:
    image: nginx:1.27
    container_name: superset_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - superset
    ports:
      - 8080:80
    networks:
        - superset_net
networks:
  superset_net:
    driver: bridge